const CFG={email:"centralservicepoint@gmail.com",whatsapp:""}; // set WhatsApp e.g. "27XXXXXXXXX"
const CATS=[["Construction","🏗️"],["Painting","🎨"],["Plumbing","🔧"],["Electrical","⚡"],["Tiling","▦"],["Roofing","🏠"],["Paving","🧱"],["Renovations","🔨"],["Building","🏢"],["Drywall","📐"],["Landscaping","🌿"],["Pools","🏊"],["Security","🔒"],["Cleaning","🧽"],["Air Conditioning","❄️"],["Welding","🔥"],["Carpentry","🪚"],["Flooring","🪵"],["Property Maintenance","🛠️"]];
const SEED=[
["Gold Painters","Painting",["Painting","Renovations","Drywall"],"Durban","KwaZulu-Natal",1,1],
["Northern Plumbing Works","Plumbing",["Plumbing","Geysers","Maintenance"],"Mahikeng","North West",1,1],
["Highveld Electrical","Electrical",["Electrical","Solar","Compliance certificates"],"Johannesburg","Gauteng",1,0],
["Cape Tile & Floor","Tiling",["Tiling","Flooring"],"Cape Town","Western Cape",1,1],
["Solid Ground Paving","Paving",["Paving","Driveways","Retaining walls"],"Potchefstroom","North West",1,0],
["Ridgeline Roofing","Roofing",["Roofing","Waterproofing"],"Pretoria","Gauteng",1,0],
["GreenEdge Landscaping","Landscaping",["Landscaping","Irrigation"],"Bloemfontein","Free State",1,0],
["Foundation Builders","Construction",["Construction","Building","Renovations"],"Klerksdorp","North West",1,1],
["Coastal Aircon Services","Air Conditioning",["Air Conditioning","Installations"],"Durban","KwaZulu-Natal",0,0]
].map((r,i)=>({id:"CSP-"+String(101+i).padStart(6,"0"),name:r[0],slug:r[0].toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/-$/,""),cat:r[1],services:r[2],city:r[3],prov:r[4],approved:!!r[5],published:!!r[5],featured:!!r[6],status:r[5]?"Approved":"Draft",phone:"0"+(10+i)+" 000 00"+(10+i),wa:"",email:"info@example.co.za",web:i%2?"":"https://example.co.za",desc:"Professional "+r[1].toLowerCase()+" services for residential and commercial properties in "+r[3]+" and surrounding areas.",areas:[r[3],r[4]],hours:"Mon–Fri 07:30–17:00, Sat 08:00–13:00",years:3+i*2,created:Date.now()-i*864e5*3,sample:1}));
const S={get(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch(e){return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}};
const FB=!!(window.CSP_CONFIG&&window.CSP_CONFIG.apiKey);let C=FB?[]:S.get("csp_c",null)||SEED,Q=FB?[]:S.get("csp_q",[]),mem={};
const save=()=>{if(FB&&window.cspSync)return window.cspSync();S.set("csp_c",C);S.set("csp_q",Q)};
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const pub=()=>C.filter(c=>c.approved&&c.published&&c.status!=="Suspended");
const ini=n=>n.split(" ").slice(0,2).map(w=>w[0]).join("");
const NAV=[["/","Home"],["/find","Find Contractors"],["/services","Services"],["/how","How It Works"],["/about","About"],["/contact","Contact"]];
function chrome(p){$("#nv").innerHTML=NAV.map(n=>`<a href="#${n[0]}" class="${p===n[0]?"on":""}">${n[1]}</a>`).join("");
$("#mm").innerHTML=NAV.map(n=>`<a class="l" href="#${n[0]}">${n[1]}</a>`).join("")+`<a class="btn" href="#/find">Find a Contractor</a><a class="btn o" href="#/list">List Your Business</a>`;
$("#mm").classList.remove("open");$("#bg").setAttribute("aria-expanded","false");
$("#wa").href=CFG.whatsapp?"https://wa.me/"+CFG.whatsapp:"mailto:"+CFG.email;}
$("#bg").onclick=()=>{const o=$("#mm").classList.toggle("open");$("#bg").setAttribute("aria-expanded",o)};
const av=c=>c.logo?`<img src="${esc(c.logo)}" alt="${esc(c.name)} logo" loading="lazy" style="width:100%;height:100%;object-fit:cover;border-radius:14px">`:esc(ini(c.name));
const gal=c=>(c.gallery&&c.gallery.length)?c.gallery.map((u,i)=>`<button data-lb="${esc(u)}" aria-label="Open gallery image ${i+1}" style="padding:0;overflow:hidden"><img src="${esc(u)}" alt="${esc(c.name)} project ${i+1}" loading="lazy" style="width:100%;height:100%;object-fit:cover"></button>`).join(""):'<p class="mut">No gallery images yet.</p>';
document.addEventListener("click",e=>{const b=e.target.closest("[data-lb]");if(b)openM(`<img src="${esc(b.dataset.lb)}" alt="" style="width:100%;border-radius:12px"><button class="btn o" style="margin-top:12px" data-x>Close</button>`)});
function seo(c){const set=(sel,a,v)=>{let e=document.head.querySelector(sel);if(!e){e=document.createElement(a[0]);e.setAttribute(a[1],a[2]);document.head.appendChild(e)}e.setAttribute(a[3],v)};
const d=c?c.desc.slice(0,155):"Search Central Service Point to discover professional contractors, explore business profiles and request a quotation.";
set('meta[name=description]',["meta","name","description","content"],d);set('meta[property="og:title"]',["meta","property","og:title","content"],document.title);
set('meta[property="og:description"]',["meta","property","og:description","content"],d);set('link[rel=canonical]',["link","rel","canonical","href"],location.href.split("?")[0]);
if(c&&(c.cover||c.logo))set('meta[property="og:image"]',["meta","property","og:image","content"],c.cover||c.logo);
let j=document.getElementById("ld");if(j)j.remove();
if(c){j=document.createElement("script");j.id="ld";j.type="application/ld+json";j.textContent=JSON.stringify({"@context":"https://schema.org","@type":"LocalBusiness",name:c.name,description:c.desc,telephone:c.phone,email:c.email,url:c.web||location.href,image:c.logo||undefined,address:{"@type":"PostalAddress",streetAddress:c.address||undefined,addressLocality:c.city,addressRegion:c.prov,addressCountry:"ZA"}});document.head.appendChild(j)}}
const card=c=>`<article class="card"><div class="fl" style="flex-wrap:nowrap"><div class="av" aria-hidden="true">${av(c)}</div><div><h3 style="margin:0;font-size:1.1rem">${esc(c.name)}</h3><div class="mut" style="font-size:.9rem">${esc(c.services.slice(0,3).join(" • "))}</div></div></div>
<p class="mut" style="margin:12px 0 6px">📍 ${esc(c.city)}, ${esc(c.prov)}</p><p style="margin:0 0 12px;font-size:.95rem">${esc(c.desc)}</p>
<div class="fl" style="margin-bottom:14px">${c.approved?'<span class="tag">✓ Approved Profile</span>':""}${c.featured?'<span class="tag f">★ Featured</span>':""}<a href="tel:${esc(c.phone.replace(/\s/g,""))}" aria-label="Call ${esc(c.name)}">📞</a>${c.web?`<a href="${esc(c.web)}" target="_blank" rel="noopener" aria-label="Website">🌐</a>`:""}</div>
<div class="fl"><a class="btn o sm" href="#/contractors/${c.slug}">View Profile</a><button class="btn sm" data-q="${c.id}">Request Quotation</button></div></article>`;
document.addEventListener("click",e=>{const b=e.target.closest("[data-q]");if(b)quoteForm(b.dataset.q);const x=e.target.closest("[data-x]");if(x)closeM();if(e.target.id==="ov")closeM()});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeM()});
function openM(h){$("#md").innerHTML=h;$("#ov").classList.add("open");const f=$("#md").querySelector("input,button");f&&f.focus()}
function closeM(){$("#ov").classList.remove("open")}
const opts=(l,sel)=>l.map(x=>`<option ${x===sel?"selected":""}>${esc(x)}</option>`).join("");
const searchBox=(s="",l="")=>`<form class="sb" id="sf" role="search"><div><label for="ss">What service do you need?</label><input id="ss" list="cl" value="${esc(s)}" placeholder="Painting, Plumbing, Electrical…"></div><div><label for="sl">Where?</label><input id="sl" value="${esc(l)}" placeholder="City, town, province or area"></div><button class="btn" style="align-self:end">Search Contractors</button></form><datalist id="cl">${CATS.map(c=>`<option>${c[0]}`).join("")}</datalist>`;
function bindSearch(){const f=$("#sf");if(f)f.onsubmit=e=>{e.preventDefault();location.hash="/find?s="+encodeURIComponent($("#ss").value)+"&l="+encodeURIComponent($("#sl").value)}}
const faqs=[["Who arranges the quotation?","Central Service Point receives your request and manages the next step manually. Quotes are not automatic."],["Are all contractors verified?","Listings marked Approved Profile have been reviewed by Central Service Point. We only describe a business as verified when it has actually been verified."],["Does it cost anything to request a quotation?","Requesting a quotation through Central Service Point is free."],["How do I list my business?","Complete the short form on the List Your Business page. We review your details before publishing."]];
const faqH=()=>faqs.map(f=>`<details><summary>${f[0]}</summary><p class="mut">${f[1]}</p></details>`).join("");
const ph=(t,s)=>`<section class="sec"><div class="w"><h1>${t}</h1><p class="mut">${s}</p></div></section>`;
function R(){
const raw=location.hash.slice(1)||"/",[path,qs]=raw.split("?"),q=new URLSearchParams(qs||""),m=$("#main");chrome(path);scrollTo(0,0);document.title="Central Service Point | Find Trusted Contractors & Service Providers";seo(null);
let h;
if(path==="/")h=home();else if(path==="/find")h=find(q);else if(path==="/services")h=services();
else if(path.startsWith("/contractors/"))h=profile(path.split("/")[2]);else if(path==="/how")h=how();else if(path==="/about")h=about();
else if(path==="/list")h=listBiz();else if(path==="/contact")h=contact();else if(path==="/faq")h=`<section class="sec"><div class="w" style="max-width:780px"><h1>Frequently Asked Questions</h1>${faqH()}</div></section>`;
else if(path==="/privacy")h=ph("Privacy Policy","Draft placeholder: replace with your POPIA-compliant policy, including how customer details in quotation requests are used and shared with contractors. This also covers cookies.");
else if(path==="/terms")h=ph("Terms & Conditions","Draft placeholder: replace with your terms, explaining that Central Service Point is a discovery platform and that work agreements are between customer and contractor.");
else if(path==="/admin")h=admin();else if(path==="/success")h=success(q);else h=`<section class="sec"><div class="w" style="text-align:center"><h1>404</h1><p class="mut">This page could not be found.</p><a class="btn" href="#/">Back to Home</a></div></section>`;
m.innerHTML=`<div class="pg">${h}</div>`;bindSearch();after(path)}
function home(){const f=pub().filter(c=>c.featured),r=[...pub()].sort((a,b)=>b.created-a.created).slice(0,3);
return `<section class="hero"><div class="w"><h1>Find Trusted Contractors & Service Providers Near You</h1><p>Search Central Service Point to discover professional contractors, compare services, explore business profiles and request a quotation from the contractor you choose.</p><div class="row"><a class="btn" href="#/find">Find a Contractor</a><a class="btn o" href="#/list">List Your Business</a></div>${searchBox()}</div></section>
<section class="sec"><div class="w"><h2>Popular Services</h2><div class="g4">${CATS.slice(0,8).map(c=>`<a class="card cat" href="#/find?s=${encodeURIComponent(c[0])}"><span>${c[1]}</span><b>${c[0]}</b></a>`).join("")}</div><p><a href="#/services">View all services →</a></p></div></section>
<section class="sec alt"><div class="w"><h2>Featured Contractors</h2>${f.length?`<div class="g3">${f.slice(0,6).map(card).join("")}</div>`:'<p class="mut">No featured contractors yet.</p>'}</div></section>
<section class="sec"><div class="w"><h2>How Central Service Point Works</h2>${steps()}</div></section>
<section class="sec alt"><div class="w"><h2>Why Use Central Service Point</h2><div class="g4">${[["Professional Contractor Listings","Reviewed before publishing."],["Easy Quote Requests","One short form per contractor."],["Local Service Discovery","Search by service and area."],["Central Service Point Support","We manage the next step."]].map(x=>`<div class="card"><h3 style="font-size:1.05rem">${x[0]}</h3><p class="mut" style="margin:0">${x[1]}</p></div>`).join("")}</div></div></section>
<section class="sec"><div class="w"><h2>Recently Listed</h2><div class="g3">${r.map(card).join("")}</div></div></section>
<section class="sec" style="padding-top:0"><div class="w"><div class="card g2" style="background:var(--g);color:#fff;align-items:center;padding:36px"><div><h2>Need a contractor?</h2><p>Search, explore profiles and request a quotation today.</p><a class="btn" style="background:#fff;color:var(--gd)" href="#/find">Find a Contractor</a></div><div><h2>Get Your Business Discovered</h2><p>List your contracting business and be found by customers.</p><a class="btn o" style="color:#fff;border-color:#fff" href="#/list">List Your Business</a></div></div></div></section>
<section class="sec alt"><div class="w" style="max-width:780px"><h2>FAQ</h2>${faqH()}</div></section>`}
function steps(){return `<div class="g3 steps">${[["01","SEARCH","Find a contractor based on the service and location you need."],["02","EXPLORE","View contractor profiles, services, contact details and portfolios."],["03","REQUEST","Submit a quotation request to the contractor you are interested in."]].map(s=>`<div class="card"><div class="n">${s[0]}</div><h3>${s[1]}</h3><p class="mut" style="margin:0">${s[2]}</p></div>`).join("")}</div><p style="margin-top:20px"><b>Central Service Point receives your request and manages the next step manually.</b></p>`}
let shown=6;
function find(q){const s=q.get("s")||"",l=q.get("l")||"";shown=6;
return `<section class="top"><div class="w"><h1>Find Contractors</h1>${searchBox(s,l)}</div></section><section class="sec" style="padding-top:28px"><div class="w">
<div class="filters"><div><label for="fc">Category</label><select id="fc"><option value="">All categories</option>${opts(CATS.map(c=>c[0]))}</select></div><div><label for="fp">Province</label><select id="fp"><option value="">All provinces</option>${opts([...new Set(C.map(c=>c.prov))].sort())}</select></div><div><label for="fso">Sort</label><select id="fso"><option>Featured first</option><option>Newest</option><option>Name A–Z</option></select></div><label class="ck"><input type="checkbox" id="ff">Featured</label><label class="ck"><input type="checkbox" id="fw">Has website</label></div>
<h2 id="rc" aria-live="polite"></h2><div class="g3" id="rs"></div><div id="em"></div><p style="text-align:center"><button class="btn o" id="lm">Load more</button></p></div></section>`}
function runFind(q){const s=(q.get("s")||"").toLowerCase(),l=(q.get("l")||"").toLowerCase();
const cat=$("#fc").value,pv=$("#fp").value,ft=$("#ff").checked,wb=$("#fw").checked,so=$("#fso").value;
let L=pub().filter(c=>(!s||[c.name,c.cat,...c.services].join(" ").toLowerCase().includes(s))&&(!l||[c.city,c.prov,...c.areas].join(" ").toLowerCase().includes(l))&&(!cat||c.cat===cat)&&(!pv||c.prov===pv)&&(!ft||c.featured)&&(!wb||c.web));
L.sort(so==="Newest"?(a,b)=>b.created-a.created:so==="Name A–Z"?(a,b)=>a.name.localeCompare(b.name):(a,b)=>b.featured-a.featured||a.name.localeCompare(b.name));
$("#rc").textContent=L.length?`${L.length} Contractors Found${s?" for "+q.get("s"):""}${l?" in "+q.get("l"):""}`:"";
$("#rs").innerHTML=L.slice(0,shown).map(card).join("");$("#lm").style.display=L.length>shown?"":"none";
$("#em").innerHTML=L.length?"":`<div class="card" style="text-align:center;padding:40px"><h2>We Couldn't Find a Contractor</h2><p class="mut">Try changing your service or location.</p><h3>Can't find what you're looking for?</h3><button class="btn" id="ra">Request Assistance</button></div>`;
const ra=$("#ra");if(ra)ra.onclick=()=>contactModal()}
function services(){return `<section class="sec"><div class="w"><h1>Services</h1><p class="mut">Choose a category to see the contractors listed for it.</p><div class="g4">${CATS.map(c=>`<a class="card cat" href="#/find?s=${encodeURIComponent(c[0])}"><span>${c[1]}</span><b>${c[0]}</b><small class="mut">${pub().filter(x=>x.cat===c[0]).length} listed</small></a>`).join("")}</div></div></section>`}
function how(){return `<section class="sec"><div class="w"><h1>How It Works</h1>${steps()}</div></section>`}
function about(){return `<section class="sec"><div class="w" style="max-width:860px"><h1>About Central Service Point</h1><p>Central Service Point is a professional marketplace designed to make finding contractors easier. Our mission is connecting customers with businesses that provide the services they need.</p><div class="g2">${[["Mission","Make it simple to discover and contact local service providers."],["Vision","A trusted, well-organised home for contractors across South Africa."],["Customer benefits","Search by service and area, compare profiles, and request quotations in one place."],["Contractor benefits","A professional profile, more visibility, and requests handled through us."],["Trust and transparency","Only approved profiles are published, and we don't call a business verified unless it is."],["Marketplace purpose","Discovery first, with Central Service Point managing the next step."]].map(x=>`<div class="card"><h3>${x[0]}</h3><p class="mut" style="margin:0">${x[1]}</p></div>`).join("")}</div></div></section>`}
function contact(){return `<section class="sec"><div class="w" style="max-width:720px"><h1>Contact</h1><p>Email: <a href="mailto:${CFG.email}">${CFG.email}</a></p><div class="card">${formHTML("c",[["name","Name"],["email","Email","email"],["phone","Phone","tel"],["subject","Subject"],["message","Message","area"]],"Send Message")}</div></div></section>`}
function listBiz(){return `<section class="sec"><div class="w" style="max-width:760px"><h1>Get Your Business Discovered</h1><p>List your contracting business on Central Service Point and make it easier for customers looking for professional services to find you.</p><div class="card">${formHTML("l",[["business","Business name"],["person","Contact person"],["phone","Phone","tel"],["whatsapp","WhatsApp","tel",1],["email","Email","email"],["website","Website","url",1],["category","Service category","cat"],["services","Services (comma separated)"],["city","Location (city/town)"],["province","Province","prov"],["description","Short business description","area"]],"Submit Listing Request")}</div></div></section>`}
const PROV=["Eastern Cape","Free State","Gauteng","KwaZulu-Natal","Limpopo","Mpumalanga","North West","Northern Cape","Western Cape"];
function formHTML(id,F,btn){return `<form id="fm-${id}" novalidate><div class="fg">${F.map(f=>{const[n,lb,t,o]=f,r=o?"":"required";let i;
if(t==="area")i=`<textarea id="${id}-${n}" name="${n}" rows="4" ${r}></textarea>`;else if(t==="cat"||t==="prov"||t==="svc")i=`<select id="${id}-${n}" name="${n}" ${r}><option value="">Select…</option>${opts(t==="prov"?PROV:CATS.map(c=>c[0]))}</select>`;
else i=`<input id="${id}-${n}" name="${n}" type="${t||"text"}" ${r}>`;
return `<div class="${t==="area"?"fw":""}"><label for="${id}-${n}">${lb}${o?" (optional)":" *"}</label>${i}<div class="err" id="e-${id}-${n}" role="alert"></div></div>`}).join("")}<div class="fw"><button class="btn">${btn}</button></div></div></form>`}
function validate(id,f){let ok=1;f.querySelectorAll("input,select,textarea").forEach(el=>{const e=$("#e-"+el.id);let m="";const v=el.value.trim();
if(el.required&&!v)m="This field is required.";else if(v&&el.type==="email"&&!/^\S+@\S+\.\S+$/.test(v))m="Enter a valid email.";else if(v&&el.type==="tel"&&!/^[+\d][\d\s()-]{6,}$/.test(v))m="Enter a valid phone number.";
else if(v&&el.type==="url"&&!/^https?:\/\//.test(v))m="Start with http:// or https://";
if(e)e.textContent=m;el.setAttribute("aria-invalid",!!m);if(m)ok=0});return ok}
function gather(f){const o={};new FormData(f).forEach((v,k)=>o[k]=String(v).trim().slice(0,2000));return o}
let last=0;
function guard(f){if(f.querySelector('[name=hp]'))return 1;return Date.now()-last>3000}
function mail(sub,body){return "mailto:"+CFG.email+"?subject="+encodeURIComponent(sub)+"&body="+encodeURIComponent(body)}
function after(path){
if(path==="/find"){const q=new URLSearchParams((location.hash.split("?")[1])||"");const go=()=>runFind(q);["fc","fp","fso","ff","fw"].forEach(i=>$("#"+i).onchange=()=>{shown=6;go()});$("#lm").onclick=()=>{shown+=6;go()};const c=CATS.find(c=>c[0].toLowerCase()===(q.get("s")||"").toLowerCase());if(c)$("#fc").value=c[0];go()}
const bind=(id,fn)=>{const f=$("#fm-"+id);if(f)f.onsubmit=e=>{e.preventDefault();if(!validate(id,f))return;fn(gather(f))}};
bind("c",d=>{window.cspMsg&&window.cspMsg(d);return done("Message ready","Send it to Central Service Point by email.",mail("Website enquiry — "+d.subject,`Name: ${d.name}\nEmail: ${d.email}\nPhone: ${d.phone}\n\n${d.message}`))});
bind("l",d=>{const id="CSP-"+(FB?String(Date.now()).slice(-8):String(101+C.length).padStart(6,"0"));C.push({id,name:d.business,slug:d.business.toLowerCase().replace(/[^a-z0-9]+/g,"-"),cat:d.category,services:d.services.split(",").map(s=>s.trim()).filter(Boolean),city:d.city,prov:d.province,approved:false,published:false,featured:false,status:"Pending",phone:d.phone,wa:d.whatsapp,email:d.email,web:d.website,desc:d.description,areas:[d.city],hours:"",years:0,created:Date.now()});save();
done("Listing request received","Your business listing request has been received. Central Service Point will review your information before publishing your profile.",mail("New Business Listing Request — "+d.business,Object.entries(d).map(([k,v])=>k+": "+v).join("\n")))});
if(path==="/admin")adminBind()}
function done(t,p,href){$("#main").innerHTML=`<section class="sec"><div class="w" style="max-width:640px;text-align:center"><div style="font-size:3rem">✅</div><h1>${t}</h1><p>${p}</p><a class="btn" href="${href}">Email to Central Service Point</a> <a class="btn o" href="#/">Back to Home</a></div></section>`;scrollTo(0,0)}
function profile(slug){const c=C.find(x=>x.slug===slug&&x.approved&&x.published);if(!c)return `<section class="sec"><div class="w" style="text-align:center"><h1>Profile not found</h1><a class="btn" href="#/find">Find Contractors</a></div></section>`;
document.title=`${c.name} | Professional ${c.cat} Contractors in ${c.city} | Central Service Point`;seo(c);
const wa=c.wa?"https://wa.me/"+c.wa.replace(/\D/g,""):"";
return `<section class="sec" style="padding-top:24px"><div class="w"><p><a href="#/find">← Find Contractors</a></p><div class="cb"${c.cover?` style="background:url('${esc(c.cover)}') center/cover"`:""}></div><div class="card" style="position:relative"><div class="fl" style="flex-wrap:nowrap"><div class="av" style="width:80px;height:80px;font-size:1.6rem">${av(c)}</div><div><h1 style="margin:0;font-size:clamp(1.5rem,4vw,2.2rem)">${esc(c.name)}</h1><div class="fl"><span class="tag">✓ Approved Profile</span><span class="mut">${esc(c.cat)} • 📍 ${esc(c.city)}, ${esc(c.prov)}</span></div></div></div><p>${esc(c.desc)}</p><button class="btn" data-q="${c.id}">REQUEST A QUOTATION</button></div>
<div class="pf" style="margin-top:24px"><div><div class="card"><h2>Services</h2><div class="fl">${c.services.map(s=>`<span class="tag">${esc(s)}</span>`).join("")}</div><h3 style="margin-top:20px">Service Areas</h3><p>${esc(c.areas.join(", "))}</p><h3>Operating Hours</h3><p>${esc(c.hours||"Contact for hours")}</p>${c.years?`<h3>Experience</h3><p>${c.years} years</p>`:""}${c.certs&&c.certs.length?`<h3>Certifications</h3><p>${c.certs.map(esc).join(", ")}</p>`:""}${c.address?`<h3>Address</h3><p>${esc(c.address)}</p>`:""}</div>
<div class="card" style="margin-top:22px"><h2>Gallery</h2><div class="gal">${gal(c)}</div></div></div>
<aside><div class="card ct"><h2>Contact</h2><a href="tel:${esc(c.phone.replace(/\s/g,""))}">📞 ${esc(c.phone)}</a>${wa?`<a href="${wa}" target="_blank" rel="noopener">💬 WhatsApp</a>`:""}${c.email?`<a href="mailto:${esc(c.email)}">✉️ ${esc(c.email)}</a>`:""}${c.web?`<a href="${esc(c.web)}" target="_blank" rel="noopener">🌐 ${esc(c.web)}</a>`:""}<a>📍 ${esc(c.city)}, ${esc(c.prov)}</a>${c.facebook?`<a href="${esc(c.facebook)}" target="_blank" rel="noopener">Facebook</a>`:""}${c.instagram?`<a href="${esc(c.instagram)}" target="_blank" rel="noopener">Instagram</a>`:""}<button class="btn" style="width:100%;margin-top:14px" data-q="${c.id}">Request a Quotation</button></div></aside></div></div></section>`}
function quoteForm(id){const c=C.find(x=>x.id===id);if(!c)return;
openM(`<h2>Request a Quotation</h2><p class="mut">Contractor: <b>${esc(c.name)}</b></p><form id="qf" novalidate><input type="text" name="hp" tabindex="-1" autocomplete="off" style="position:absolute;left:-999px" aria-hidden="true"><div class="fg">
<div><label for="q1">Full Name *</label><input id="q1" name="name" required><div class="err" id="e-q1"></div></div>
<div><label for="q2">Phone Number *</label><input id="q2" name="phone" type="tel" required><div class="err" id="e-q2"></div></div>
<div><label for="q3">Email Address *</label><input id="q3" name="email" type="email" required><div class="err" id="e-q3"></div></div>
<div><label for="q4">Your Location *</label><input id="q4" name="loc" required><div class="err" id="e-q4"></div></div>
<div><label for="q5">Service Required *</label><select id="q5" name="service" required>${opts(c.services)}</select><div class="err" id="e-q5"></div></div>
<div><label for="q6">Project Location *</label><input id="q6" name="ploc" required><div class="err" id="e-q6"></div></div>
<div class="fw"><label for="q7">Project Description *</label><textarea id="q7" name="desc" rows="4" required></textarea><div class="err" id="e-q7"></div></div>
<div><label for="q8">Preferred Date</label><input id="q8" name="date" type="date"></div>
<div><label for="q9">Budget Range (optional)</label><input id="q9" name="budget" placeholder="e.g. R20,000"></div>
<div class="fw"><label for="q10">Additional Information</label><textarea id="q10" name="extra" rows="2"></textarea></div>
<div class="fw note">File and photo uploads need the server component. Mention attachments above and Central Service Point will follow up.</div>
<div class="fw fl"><button class="btn">Submit Request</button><button type="button" class="btn o" data-x>Cancel</button></div></div></form>`);
$("#qf").onsubmit=e=>{e.preventDefault();const f=e.target;
[...f.querySelectorAll("[required]")].forEach(el=>{const er=$("#e-"+el.id);let m=!el.value.trim()?"This field is required.":(el.type==="email"&&!/^\S+@\S+\.\S+$/.test(el.value)?"Enter a valid email.":"");er.textContent=m;el.setAttribute("aria-invalid",!!m)});
if(f.querySelector("[aria-invalid=true]"))return;const d=gather(f);if(d.hp)return;
const ref="CSP-QUOTE-"+String(Math.floor(Math.random()*1e6)).padStart(6,"0");
Q.unshift({ref,date:new Date().toISOString(),contractorId:c.id,contractorName:c.name,name:d.name,phone:d.phone,email:d.email,service:d.service,ploc:d.ploc,desc:d.desc,date2:d.date,budget:d.budget,extra:d.extra,status:"New",notes:""});save();
mem.mail=mail(`New Quotation Request — ${c.name} — ${d.name}`,`NEW CENTRAL SERVICE POINT QUOTATION REQUEST\n\nContractor Requested:\n${c.name}\n\nContractor ID:\n${c.id}\n\nReference:\n${ref}\n\nCustomer Name:\n${d.name}\n\nCustomer Phone:\n${d.phone}\n\nCustomer Email:\n${d.email}\n\nProject Location:\n${d.ploc}\n\nService Required:\n${d.service}\n\nProject Description:\n${d.desc}\n\nPreferred Date:\n${d.date}\n\nBudget:\n${d.budget}\n\nAdditional Information:\n${d.extra}\n\nContractor Contact Information:\nPhone: ${c.phone}\nWhatsApp: ${c.wa}\nEmail: ${c.email}\nWebsite: ${c.web}`);
closeM();location.hash="/success?ref="+ref}}
function success(q){return `<section class="sec"><div class="w" style="max-width:640px;text-align:center"><div style="font-size:3rem">✅</div><h1>Request Received Successfully</h1><p>Thank you. Your quotation request has been received by Central Service Point.</p><p>We will review your request and assist with the next steps. Central Service Point manages the next communication; a quotation is not sent automatically.</p><p>Reference Number:<br><b style="font-size:1.4rem">${esc(q.get("ref"))}</b></p>${mem.mail?`<a class="btn" href="${mem.mail}">Send request email to Central Service Point</a> `:""}<a class="btn o" href="#/">Back to Home</a><p class="note" style="margin-top:20px">Prototype: with no server, the email is sent from your own mail app via the button above.</p></div></section>`}
const STAT=["New","Reviewing","Contractor Contacted","Customer Contacted","In Progress","Completed","Closed"];
function admin(){return `<section class="sec"><div class="w"><h1>Admin Dashboard</h1><p class="note">Prototype only: data is stored in this browser and this page has no real login. A production build needs server-side authentication and a database before any of this is exposed.</p>
<h2 style="margin-top:28px">Contractors</h2><div class="tbl card"><table><tr><th>ID</th><th>Business</th><th>Status</th><th>Actions</th></tr>${C.map(c=>`<tr><td>${c.id}</td><td>${esc(c.name)}<br><small class="mut">${esc(c.city)}</small></td><td>${c.approved?"Approved":c.status}${c.published?" • Published":" • Unpublished"}${c.featured?" • ★":""}</td><td class="fl"><button class="btn o sm" data-a="ap" data-i="${c.id}">${c.approved?"Unapprove":"Approve"}</button><button class="btn o sm" data-a="pu" data-i="${c.id}">${c.published?"Unpublish":"Publish"}</button><button class="btn o sm" data-a="fe" data-i="${c.id}">${c.featured?"Unfeature":"Feature"}</button><button class="btn o sm" data-a="su" data-i="${c.id}">${c.status==="Suspended"?"Reinstate":"Suspend"}</button><button class="btn o sm" data-a="de" data-i="${c.id}">Delete</button></td></tr>`).join("")}</table></div>
<h2 style="margin-top:28px">Quotation Requests</h2>${Q.length?`<div class="tbl card"><table><tr><th>Ref / Date</th><th>Customer</th><th>Contractor</th><th>Request</th><th>Status & Notes</th></tr>${Q.map((x,i)=>`<tr><td>${x.ref}<br><small>${x.date.slice(0,10)}</small></td><td>${esc(x.name)}<br>${esc(x.phone)}<br>${esc(x.email)}</td><td>${esc(x.contractorName)}<br><small>${x.contractorId}</small></td><td>${esc(x.service)} — ${esc(x.ploc)}<br><small>${esc(x.desc)}</small></td><td><select data-s="${i}" aria-label="Status">${opts(STAT,x.status)}</select><textarea data-n="${i}" rows="2" placeholder="Admin notes" style="margin-top:6px">${esc(x.notes)}</textarea></td></tr>`).join("")}</table></div>`:'<p class="mut">No requests yet.</p>'}</div></section>`}
function adminBind(){document.querySelectorAll("[data-a]").forEach(b=>b.onclick=()=>{const c=C.find(x=>x.id===b.dataset.i),a=b.dataset.a;
if(a==="ap"){c.approved=!c.approved;c.status=c.approved?"Approved":"Draft"}else if(a==="pu")c.published=!c.published;else if(a==="fe")c.featured=!c.featured;else if(a==="su")c.status=c.status==="Suspended"?"Approved":"Suspended";else if(a==="de"&&confirm("Delete "+c.name+"?"))C=C.filter(x=>x!==c);save();R()});
document.querySelectorAll("[data-s]").forEach(s=>s.onchange=()=>{Q[s.dataset.s].status=s.value;save()});
document.querySelectorAll("[data-n]").forEach(s=>s.onchange=()=>{Q[s.dataset.n].notes=s.value;save()})}
function contactModal(){openM(`<h2>Request Assistance</h2>${formHTML("c",[["name","Name"],["email","Email","email"],["phone","Phone","tel"],["subject","Subject"],["message","What are you looking for?","area"]],"Send Request")}<button class="btn o" style="margin-top:10px" data-x>Cancel</button>`);
const f=$("#fm-c");f.onsubmit=e=>{e.preventDefault();if(!validate("c",f))return;const d=gather(f);window.cspMsg&&window.cspMsg(d);closeM();done("Request ready","Send it to Central Service Point by email.",mail("Assistance request — "+d.subject,`Name: ${d.name}\nEmail: ${d.email}\nPhone: ${d.phone}\n\n${d.message}`))}}
addEventListener("hashchange",R);R();
